name: Docker Image CI

on:
  push:
    branches: 
      - main
 
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Update Version
        run: |
          VERSION=$(cat version.txt)
          
          NEW_VERSION=$(echo $VERSION | awk -F. '{printf("%d.%d.%d", $1,$2,$3+1)}')
          
          echo $NEW_VERSION > version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Login to Github Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u USERNAME --password-stdin docker.pkg.github.com

      - name: Determine Version
        run: echo ::set-output name=version::$(cat version.txt)
        id: get-version

      - name: Build the Docker Image
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/test:${{ steps.get-version.outputs.version }} .

      - name: Push the Docker Image
        run: docker push docker.pkg.github.com/${{ github.repository }}/test:${{ steps.get-version.outputs.version }}
